### ISSUE TITLE
Passwort hashing 

### ISSUE THREAD

**Issue by BenniN** [DomenicDev/pms#14]

**Comment by Colovan** [comment]
implemented in de.hfu.pms-shared.SHA

**Comment by DomenicDev** [comment]
Thanks for that contribution. In my last commit I removed the hashing of the password.
The reason for that is, that on server side we also encrypt the password with a special password encoder. If we would keep the SHA-256 algorithm we would encode the already hashed password which might be a bit too much, I don't now....
What do you think?
