### ISSUE TITLE
date fields in employment relationships and promotions have to be added to the FormValidaator

### ISSUE THREAD

**Issue by BenniN** [DomenicDev/pms#31]
The date fields don't take over data from typing in a date but will do when picked out of the calendar. So they have to be generally have to be Formvalidated and should check if the textfield isn't empty and could be set as a vaild date

**Comment by DomenicDev** [comment]
This has been fixed with on of the latest commits, including https://github.com/DomenicDev/pms/commit/b382452a7261087007da191a39dea5438287b33e and https://github.com/DomenicDev/pms/commit/6ba95dbf15c11d97a08f9197506cfd6b0ccf20c9

Thanks for the bug report! 👍
