### ISSUE TITLE
5 Promotions add screen failures

### ISSUE THREAD

**Issue by BenniN** [DomenicDev/pms#35]
-the upper left screen always alerts with a non helpfull message and you cant add anything.
-the upper right table never takes the sum in the list.
-buttom left throws same non helpfull exception but is able to add somthing 
-buttom left works 
-deletebutton works everywhere
-no validation at all (already in another issu) you are able to add empty lines

**Comment by DomenicDev** [comment]
This should be fixed with the latest commit
